name: Ping Render App

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:        # Lets you trigger it manually if needed

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping the Flask app on Render
        run: curl -sSf https://abhisheks-todo-app.onrender.com/ || echo "Ping failed"
