name: Keep Render App Alive

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes (UTC)
  workflow_dispatch:         # Allows manual trigger from GitHub Actions tab

jobs:
  ping-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run keep-alive script
        run: python main.py
